print("Hello World")
print("hello team")
print("My Name is Jazz")
print("my name is andy")
print("My name is Rachel")
print("My name is Justin")
print("Hello World")
print ("My name is nancy!")
print("Last push")
print ("Im sorry that my laptop sucks")